export type FmField = { key: string; label: string }

// FM リスト情報 の全フィールド（mappers.ts の mapFMListToSupabase と対応）
export const FM_FIELDS_LIST_RECORDS: FmField[] = [
  { key: '顧客ID',           label: '顧客ID' },
  { key: 'ADNAME',           label: '広告名（ADNAME）' },
  { key: 'リスト譲渡日',     label: 'リスト譲渡日' },
  { key: 'リスト',           label: 'リスト名' },
  { key: '業種',             label: '業種' },
  { key: '新人フラグ',       label: '新人フラグ（担当者）' },
  { key: 'リスト作成日時',   label: 'リスト作成日時（＝問い合わせ日）' },
  { key: '会社名',           label: '会社名' },
  { key: '代表名',           label: '代表者名' },
  { key: '役職',             label: '役職' },
  { key: '定休日',           label: '定休日（月火水木金）' },
  { key: '都道府県',         label: '都道府県' },
  { key: '電話番号',         label: '電話番号（複数可）' },
  { key: 'メールアドレス',   label: 'メールアドレス（会社）' },
  { key: '営業開始時間',     label: '営業開始時間' },
  { key: '営業終了時間',     label: '営業終了時間' },
  { key: 'ホームページ有無', label: 'ホームページ有無（有/無）' },
  { key: '住所',             label: '住所' },
  { key: '再コール日',       label: '再コール日' },
  { key: '再コール時刻',     label: '再コール時刻' },
  { key: 'リスト精査',       label: 'リスト精査（ゲキアツ/とりこぼし）' },
  { key: 'ホームページURL',  label: 'ホームページURL' },
  { key: 'MEO',              label: 'MEO（複数チェック）' },
  { key: '案件メモ',         label: '案件メモ' },
  { key: '商談日',           label: '商談日' },
  { key: '商談時刻',         label: '商談時刻' },
  { key: '担当ZOOM',         label: '担当ZOOMリンク' },
  { key: 'ZOOMPW',           label: 'ZOOM パスワード' },
  { key: 'ZOOMID',           label: 'ZOOM ID' },
  { key: 'ZOOMリンク',       label: 'ZOOMリンク' },
  { key: '件名',             label: 'メール件名' },
  { key: '本文',             label: 'メール本文' },
  { key: '最終担当者名',     label: '最終コール担当者' },
  { key: '最終代表レベル',   label: '最終代表レベル' },
  { key: '最終対応レベル',   label: '最終担当レベル' },
  { key: '最終代表hit',      label: '最終代表hit' },
  { key: '最終対応カテゴリ', label: '最終対応カテゴリ' },
  { key: '最終リストレベル', label: '最終リストレベル' },
  { key: '最終コール開始時刻', label: '最終コール開始時刻' },
  { key: '最終コール終了時刻', label: '最終コール終了時刻' },
  { key: '最終コール時間_秒', label: '最終コール時間（秒）' },
  { key: '最終コール時間_分', label: '最終コール時間（分）' },
  { key: '最終アポ情報詳細', label: '最終アポ情報詳細' },
  { key: '最終CL',           label: '最終CL' },
  { key: '最終コール結果',   label: '最終コール結果' },
  { key: '最終コール開始日', label: '最終コール日' },
]

// FM コール履歴 の全フィールド（mappers.ts の mapFMCallToSupabase と対応）
export const FM_FIELDS_CALLS: FmField[] = [
  { key: '顧客ID',           label: '顧客ID' },
  { key: '対応履歴ID',       label: '対応履歴ID' },
  { key: 'コール結果',       label: 'コール結果' },
  { key: 'コール開始日',     label: 'コール開始日' },
  { key: 'コール開始時刻',   label: 'コール開始時刻' },
  { key: 'コール終了時刻',   label: 'コール終了時刻' },
  { key: 'コール時間_分',    label: 'コール時間（分）' },
  { key: 'コール時間_秒',    label: 'コール時間（秒）' },
  { key: 'クラリスID',       label: 'クラリスID' },
  { key: '担当者名',         label: '担当者名' },
  { key: '代表hit',          label: '代表hit' },
  { key: 'CL',               label: 'CL' },
  { key: 'リストレベル',     label: 'リストレベル' },
  { key: '代表レベル',       label: '代表レベル' },
  { key: '対応カテゴリ',     label: '対応カテゴリ' },
  { key: '担当レベル',       label: '担当レベル' },
  { key: 'アポ情報詳細',     label: 'アポ情報詳細' },
  { key: '非表示',           label: '非表示フラグ' },
  { key: 'リスト仕入れ先',   label: 'リスト仕入れ先' },
  { key: '問い合わせ日',     label: '問い合わせ日' },
  { key: 'リスト',           label: 'リスト名' },
]

// Supabase list_records カラム一覧（supabase.ts の型定義と一致）
export const SUPABASE_COLS_LIST_RECORDS: FmField[] = [
  { key: 'customer_id',          label: '顧客ID' },
  { key: 'ad_name',              label: '広告名（ADNAME）' },
  { key: 'list_handover_date',   label: 'リスト譲渡日' },
  { key: 'list_name',            label: 'リスト名' },
  { key: 'industry',             label: '業種' },
  { key: 'newcomer_flag',        label: '新人フラグ' },
  { key: 'list_created_at',      label: 'リスト作成日時（問い合わせ日）' },
  { key: 'company_name',         label: '会社名' },
  { key: 'representative_name',  label: '代表者名' },
  { key: 'title',                label: '役職' },
  { key: 'regular_holidays',     label: '定休日' },
  { key: 'prefecture',           label: '都道府県' },
  { key: 'phone_numbers',        label: '電話番号' },
  { key: 'company_email',        label: 'メールアドレス' },
  { key: 'business_start_time',  label: '営業開始時間' },
  { key: 'business_end_time',    label: '営業終了時間' },
  { key: 'homepage_exists',      label: 'ホームページ有無' },
  { key: 'address',              label: '住所' },
  { key: 'recall_date',          label: '再コール日' },
  { key: 'recall_time',          label: '再コール時刻' },
  { key: 'list_screening',       label: 'リスト精査' },
  { key: 'homepage_url',         label: 'ホームページURL' },
  { key: 'meo_status',           label: 'MEO状況' },
  { key: 'case_memo',            label: '案件メモ' },
  { key: 'meeting_date',         label: '商談日' },
  { key: 'meeting_time',         label: '商談時刻' },
  { key: 'zoom_url',             label: 'ZOOMリンク（担当）' },
  { key: 'zoom_pw',              label: 'ZOOM PW' },
  { key: 'zoom_id',              label: 'ZOOM ID' },
  { key: 'zoom_link',            label: 'ZOOMリンク' },
  { key: 'email_subject',        label: 'メール件名' },
  { key: 'email_body',           label: 'メール本文' },
  { key: 'last_call_agent',      label: '最終コール担当者' },
  { key: 'last_call_rep_level',  label: '最終代表レベル' },
  { key: 'last_call_rep_level2', label: '最終担当レベル' },
  { key: 'last_call_category',   label: '最終対応カテゴリ' },
  { key: 'last_call_start_time', label: '最終コール開始時刻' },
  { key: 'last_call_end_time',   label: '最終コール終了時刻' },
  { key: 'last_call_appo_detail', label: '最終アポ情報詳細' },
  { key: 'last_call_result',     label: '最終コール結果' },
  { key: 'last_call_date',       label: '最終コール日' },
]

// Supabase calls カラム一覧
export const SUPABASE_COLS_CALLS: FmField[] = [
  { key: 'customer_id',           label: '顧客ID（FMから）' },
  { key: 'call_result',           label: 'コール結果' },
  { key: 'call_date',             label: 'コール日' },
  { key: 'call_start_time',       label: 'コール開始時刻' },
  { key: 'call_end_time',         label: 'コール終了時刻' },
  { key: 'call_duration_minutes', label: 'コール時間（分）' },
  { key: 'agent_name',            label: '担当者名' },
  { key: 'rep_hit',               label: '代表hit' },
  { key: 'ci',                    label: 'CL' },
  { key: 'rep_level',             label: 'リストレベル' },
  { key: 'daihyo_level',          label: '代表レベル' },
  { key: 'call_category',         label: '対応カテゴリ' },
  { key: 'rep_level2',            label: '担当レベル' },
  { key: 'appo_detail',           label: 'アポ情報詳細' },
  { key: 'list_source',           label: 'リスト仕入れ先' },
  { key: 'inquiry_date',          label: '問い合わせ日' },
  { key: 'list_name',             label: 'リスト名' },
  { key: 'newcomer_flag',         label: '新人フラグ' },
]
