ALTER TABLE leads ADD COLUMN IF NOT EXISTS appo_detail_status TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS appo_date DATE;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS appo_time TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS appo_detail TEXT;
